Creating test_pycgm_utils.py
cadop/pyCGM pull request #30
Opened 2020-10-13 19:11 UTC by thepeytongreen

2020-11-14 16:44 UTC, cadop commented
Are the two exception functions that have problems being called/used anywhere in the repo?

2020-11-14 16:52 UTC, thepeytongreen commented
@cadop normDiv is not. I have previously created an issue for it and we were going to delete it once unit tests were finished. matrixmult is used. It returns the correct result if given valid matrices, it just doesn't have an exception for when the dimensions aren't correct

2020-11-17 01:12 UTC, cadop requested changes

2020-11-17 01:12 UTC, cadop commented on pyCGM_Single/tests/test_pycgm_utils.py
> +        containing the right wand marker x,y,z positions (1x3) followed by the left wand marker x,y,z positions (1x3).
Can you expand on what the wand marker is for this test.  I think this function is really the most important one in the file here.

2020-11-22 16:52 UTC, cadop approved these changes

2020-11-22 16:52 UTC, merged