Creating test_pycgmKintetics.py
cadop/pyCGM pull request #33
Opened 2020-10-23 06:36 UTC by GVeras

Adding unit tests to **pycgmKintetics.py.**

2020-10-28 19:37 UTC, cadop requested changes

2020-10-28 19:37 UTC, cadop commented on pyCGM_Single/tests/test_pycgmKinetics.py
> +    def testF(self):
these should start with `test_`

2020-10-30 21:22 UTC, GVeras commented on pyCGM_Single/tests/test_pycgmKinetics.py
> +    def testF(self):
Resolved, fixed all the function names.

2020-10-31 01:31 UTC, GVeras commented on pyCGM_Single/tests/test_pycgmKinetics.py
> +        accuracyTests=[
I added better comments/documentation to all the functions.

2020-10-31 20:15 UTC, merged