Docstring Changes
cadop/pyCGM pull request #74
Opened 2021-02-26 21:35 UTC by jm786

2021-03-01 21:49 UTC, cadop requested changes

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    It is rotated from incorrect axis in YXZ order.
uncorrected

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    Takes in anatomically incorrect axis and anatomically correct axis.
uncorrected

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    The correct axis changes depending on flat-footedness.
`flat foot` is correct.

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    (anatomically incorrect foot axis)
uncorrected

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    If flat-footed, make the reference markers instead of HEE marker whose height
flat foot

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +        Returns a list that contain the toe axis' (right and left) origin in 1x3 arrays
foot, not toe

2021-03-01 21:49 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    """Calculate the anatomically incorrect foot joint center and axis function.
uncorrected

2021-03-06 15:06 UTC, cadop requested changes

2021-03-06 15:06 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    [array([364.24453179, 292.34485083, 515.31187596]),
...

2021-03-06 15:06 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    [array([393.76163633, 247.67765724,  87.73637664]),
...

2021-03-06 15:06 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +            [441.89356133, 381.9962754 ,  42.67132275],
...

2021-03-17 02:16 UTC, jm786 commented
I made the changes requested; all doctests are now rounded to two decimal places.

2021-03-17 12:43 UTC, cadop requested changes
One issue with rounding. 

test_pycgmStatic is not a docstring, its a unittest. Please undo.

2021-03-17 12:43 UTC, cadop commented on pyCGM_Single/pycgmStatic.py
> +    array([[183.23960265, 338.80485163, 934.65192157],
rounding

2021-03-23 21:41 UTC, cadop approved these changes

2021-03-23 21:41 UTC, merged